### ISSUE TITLE
[Question] making this a separate controller

### ISSUE THREAD

**Issue by boeboe** [aws-samples/eks-automated-ipmgmt-multus-pods#1]
Hi,

Are there any plans or is there any community interest to make this functionality available as a separate (potentially GoLang based) controller with a reconciliation loop? This way, no sidecar nor init container is needed and the solution would be fully transparent to the deployment of applications.

Best regards,
Bart

**Comment by raghs-aws** [comment]
Hi Bart,

Not yet, I have written a daemonset pods which can perform this task, will try to publish it on this repo, in next few days.  That solution is still not tested for big deployments and doesn't work with DPDK based pods and works for the ipvlan pods.
 
Will publish it soon.

Thanks,
Raghvendra Singh

**Comment by raghs-aws** [comment]
Kindly reopen the issue, if you are not satisfied with the issue. I clicked wrong button :)

**Comment by raghs-aws** [comment]
Hi, not in go lang but i created a daemonset solution which doesnt need any sidecar or initcontainer in the pod spec. The language used is python , check if this is ok, https://github.com/aws-samples/eks-nonintrusive-automated-ipmgmt-multus-pods
