### ISSUE TITLE
Can I assign EIPs to pods?

### ISSUE THREAD

**Issue by iciclespider** [aws-samples/eks-automated-ipmgmt-multus-pods#3]
Is it possible to end up with EIPs assigned to pods? If so, can you provide me with some general pointers to what is involved?

**Comment by raghs-aws** [comment]
you mean EIP on multus interfaces? if its not multus then you usually do via ALB or NLB with EIP

**Comment by iciclespider** [comment]
I do mean on multus interfaces. I do not want either type of load balancer involved.

**Comment by raghs-aws** [comment]
yes its possible, in that case, code enhancement needed to assign and reassign the elastic IP on multus interfaces in the init/sidecar container code

**Comment by iciclespider** [comment]
Oh, I see! Thanks for the confirmation.
