### ISSUE TITLE
Cross AZ IP pool

### ISSUE THREAD

**Issue by flostadler** [aws-samples/eks-automated-ipmgmt-multus-pods#4]
Based on the NetworkAttachmentDefinition provided in this repo, I couldn't get this working with multiple AZs. Every AZ has its own subnet with its own CIDR, but for a multi AZ deployment we'd need to be able to pick the right CIDR for the current subnet during IP allocation.

Does this mean Multus on EKS can only be used in a non HA setup?

**Comment by raghs-aws** [comment]
Multus depends on the IP subnet used on the worker nodes, and subnets are tied to an availability zone. if you need multi-AZ then you would have to ensure that right IP address (for the underlying subnet on worker) is used. For multi-az setup you can use different node-selectors and different Multus NADs to handle IPs in separate AZ.

**Comment by raghs-aws** [comment]
if you need same IP to filaover across AZ on multus the you would have to use slightly different solution as mentioned in blog https://aws.amazon.com/blogs/industries/automated-application-failover-across-availability-zones-with-floating-virtual-ip-on-amazon-eks/

**Comment by raghs-aws** [comment]
closing issue as no response received. please reopen if your query is unresolved.
